server:
  port: 8089
  servlet:
#    context-path: /web
    #以下三行配置信息，修改jsp文件不用重启
    jsp:
      init-parameters:
        development: true
spring:
  datasource: #简单测试,这里不设数据库连接池
    name: moudle  #数据库名
    url: jdbc:mysql://localhost:3306/moudle?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root  #用户名
    password: myroot  #密码
    #    driver-class-name: com.mysql.jdbc.Driver #数据库连接驱动
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库连接驱动(版本8以上，兼容低版本)
  mvc:
    view:
      prefix: /WEB-INF/jsp/ #jsp文件夹映射路径
      suffix: .jsp #省略文件后最
  jpa:
    open-in-view: false
#  thymeleaf:
#    cache: false
#    enabled: false
#mybatis映射路径
mybatis:
  mapper-locations: classpath:mybatis/*/*.xml,mybatis/**/*.xml

